#!/usr/bin/env bash

set -euxo pipefail

# Settings.
EMACS_HOME=~/.emacs.d
STRAIGHT_VERSIONS="${EMACS_HOME}/straight/versions"

mkdir -p "${STRAIGHT_VERSIONS}"

for i in lisp snippets; do
  rm -rf "${EMACS_HOME:?}/${i}"
done

cp early-init.el init.el "${EMACS_HOME}"
cp package-lock.el "${STRAIGHT_VERSIONS}/default.el"

for i in lisp snippets; do
  cp -r "./${i}" "${EMACS_HOME}"
done

for i in auto-save backups elfeed; do
  mkdir -p "${EMACS_HOME:?}/${i}"
done
