#!/usr/bin/env bash

set -euxo pipefail

if [[ "${OSTYPE}" = darwin* ]]; then
  brew install \
    enchant \
    font-jetbrains-mono \
    git \
    gopls \
    llvm \
    pipx \
    pkg-config \
    ripgrep \
    uv

  pipx install \
       pyright

  exit 0
fi

# shellcheck source=/dev/null
source /etc/os-release

if [[ "${ID}" = fedora ]]; then
  sudo dnf install \
       clang \
       enchant2 \
       enchant2-devel \
       coreutils \
       git \
       gopls \
       jetbrains-mono-fonts \
       libsqlite3x-devel \
       pipx \
       pkgconf-pkg-config \
       ripgrep \
       uv \
       wl-clipboard

  pipx install \
       pyright

  exit 0
fi

echo "OS is not supported!"

exit 1
