#!/usr/bin/env bash

set -euxo pipefail

if [[ "${OSTYPE}" = darwin* ]]; then
  brew tap d12frosted/emacs-plus
  brew trust --formula d12frosted/emacs-plus/emacs-plus@31

  brew install emacs-plus@31 \
    --with-xwidgets \
    --formula

  brew install \
    claude-code \
    cmake \
    enchant \
    font-jetbrains-mono \
    git \
    gopls \
    libterm \
    llvm \
    pipx \
    pkg-config \
    ripgrep \
    uv

  brew install --cask mactex

  pipx install \
       pyright

  exit 0
fi

# shellcheck source=/dev/null
source /etc/os-release

if [[ "${ID}" = fedora ]]; then
  sudo dnf install \
       clang \
       cmake \
       enchant2 \
       enchant2-devel \
       coreutils \
       git \
       golang \
       jetbrains-mono-fonts \
       libsqlite3x-devel \
       libvterm \
       pipx \
       pkgconf-pkg-config \
       ripgrep \
       util-linux \
       uv \
       wl-clipboard

  pipx install \
       pyright

  go install \
     golang.org/x/tools/gopls@latest

  exit 0
fi

if [[ "${ID}" = debian ]]; then
    sudo apt-get install \
         clang \
         cmake \
         libenchant-2-2 \
         libenchant-2-dev \
         git \
         golang \
         fonts-jetbrains-mono \
         libsqlite3-dev \
         libvterm-dev \
         ripgrep \
         pipx \
         wl-clipboard

    pipx install \
         pyright \
         uv

    go install \
       golang.org/x/tools/gopls@latest

  exit 0
fi

echo "OS is not supported!"

exit 1
